### ISSUE TITLE
matrix-client does not store account info into cached token file now

### ISSUE THREAD

**Issue by stardiviner** [jgkamat/matrix-client-el#66]
In the latest version of Git master branch, matrix-client seems does not save account info into a cached token file now.

**Comment by alphapapa** [comment]
Sorry that I didn't notice this issue sooner.  I usually search for issues in my repos, but since this under Jay's account, it didn't show up, and I forgot to check these issues.

I don't know why it the token saving wouldn't work.  It works for me.  The option is not enabled by default, so ensure that it is turned on.
